# 配置端口
server:
  port: 8861
dubbo:
  # 配置服务信息
  application:
    name: dubbo-provider
  # 配置注册中心
  registry:
    address: nacos://localhost:8848
  # 设置协议-协议由提供方指定消费方被动接受
  protocol:
    name: dubbo
    port: 20880
spring:
  main:
    # 解决Bean重复定义问题
    allow-bean-definition-overriding: true
